web/router.ex
defmodule Chatex.Router do
  use Chatex.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Chatex do
    pipe_through :browser # Use the default browser stack

    get "/", RoomsController, :show, as: :lobby
    get "/:id", RoomsController, :show, as: :room
  end

  # Other scopes may use custom stacks.
  # scope "/api", Chatex do
  #   pipe_through :api
  # end
end

lib/chatex/endpoint.ex
defmodule Chatex.Endpoint do
  use Phoenix.Endpoint, otp_app: :chatex

  socket "/socket", Chatex.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :chatex, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_chatex_key",
    signing_salt: "+591Dv9c"

  plug Chatex.Router
end

web/controllers/page_controller.ex
defmodule Chatex.PageController do
  use Chatex.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/rooms_controller.ex
defmodule Chatex.RoomsController do
  use Phoenix.Controller

  @default_room "Lobby"

  @doc "shows a specific room with room_id specified"
  def show(conn, %{ "id" => room_id }) do
    conn |> render_room room_id
  end

  @doc "show a default room -- Lobby"
  def show(conn, _params) do
    conn |> render_room @default_room
  end

  # renders the room with given ID
  defp render_room(conn, room_id) do
    conn |> render :show, room_id: room_id
  end
end

web/views/error_view.ex
defmodule Chatex.ErrorView do
  use Chatex.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Chatex.LayoutView do
  use Chatex.Web, :view
end

web/views/page_view.ex
defmodule Chatex.PageView do
  use Chatex.Web, :view
end

web/views/rooms_view.ex
defmodule Chatex.RoomsView do
  use Chatex.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Chatex</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  </head>

  <body>
    <div class="container" role="main">

      <%= @inner %>

    </div> <!-- /container -->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2>Welcome to Phoenix!</h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="http://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/rooms/show.html.eex
<div class="row">
  <div class="col-sm-4">
    <h2>Rooms</h2>
    <ul id="rooms">
      <li><a href="<%= lobby_path(@conn, :show) %>">Lobby</a></li>
      <li><a href="<%= room_path(@conn, :show, "Help") %>">Help</a></li>
    </ul>
  </div>
  <div class="col-sm-8">
    <h1><%= @room_id %></h1>
    <div id="chatbox"></div>

    <div id="chatline">
      <form>
        <input type="hidden" name="_csrf_token" id="csrf_tk" value="<%= get_csrf_token() %>">
        <input type="hidden" name="room_id" id="room_id" value="<%= @room_id %>">
        <div class="form-group">
          <div class="row">
            <div class="col-sm-4">
              <input type="text" name="user" id="user" placeholder="User name" class="form-control"/>
            </div>
            <div class="col-sm-7">
              <input type="text" name="body" id="body" placeholder="Message" class="form-control"/>
            </div>
            <div class="col-sm-1">
              <input id="submit" type="submit" class="btn btn-default" value="Say"/>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>